AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for S3 trigger
Resources:
  ProcessImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["app.lambda_handler"]
      Timeout: 900
      MemorySize: 5240
      Environment:
        Variables:
          AWS_DEFAULT_REGION: ap-south-1
          DYNAMODB_TABLE: L1C  # Match the actual table name
          DYNAMODB_ENDPOINT: https://dynamodb.ap-south-1.amazonaws.com
          SOURCE_BUCKET: kdg-raw
          DESTINATION_BUCKET: final-cog
          AWS_ACCESS_KEY_ID: AKIAWEJRDA3QOVOK5EWE
          AWS_SECRET_ACCESS_KEY: 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
          DYNAMODB_REGION: ap-south-1
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
                - s3:HeadObject
              Resource: 
                - !Sub 'arn:aws:s3:::kdg-raw/*'
                - !Sub 'arn:aws:s3:::kdg-raw'
            - Effect: Allow 
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
              Resource:
                - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Files'
        - S3ReadPolicy:
            BucketName: kdg-raw
        - S3CrudPolicy:
            BucketName: final-cog
        - S3WritePolicy:
            BucketName: final-cog
        - DynamoDBCrudPolicy:
            TableName: satellite-metadata
        - DynamoDBCrudPolicy:
            TableName: L1C
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket: !Ref SourceBucket
            Events: s3:ObjectCreated:*
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./hello_world
      DockerTag: python3.9-v1
  SourceBucket:
    Type: AWS::S3::Bucket
    
  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: final-cog
  MetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: L1C
      AttributeDefinitions:
        - AttributeName: date
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: date
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      Region: ap-south-1